{
 "title": "Fly Edge",
 "tags": [ "fly" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "source", "query": "prometheus" },
   {
    "name": "app",
    "query": {
     "query": "label_values(fly_edge_data_in, app)"
    }
   },
   {
    "name": "region",
    "query": {
     "query": "label_values(fly_edge_data_in{app=\"$app\"}, region)"
    }
   },
   {
    "name": "host",
    "query": {
     "query": "label_values(fly_edge_data_in{app=\"$app\", region=\"$region\"}, host)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Data",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Data Out",
     "type": "geomap",
     "gridPos": { "h": 10, "w": 10, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "label_uppercase(sum(rate(fly_edge_data_out{app=\"$app\"}[$__range]))by(region), \"region\")",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Data In / Out",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 14, "x": 10, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(fly_edge_data_in{app=~\"$app\", region=~\"$region\", host=~\"$host\"}))",
       "legendFormat": "Total In"
      },
      {
       "expr": "topk_avg(5,\n  sum(rate(fly_edge_data_in\n    {app=~\"$app\",region=~\"$region\", host=~\"$host\"}))by(region)\n, \"region=other\") > 0",
       "legendFormat": "{{region}}"
      },
      {
       "expr": "sum(rate(fly_edge_data_out{app=~\"$app\", region=~\"$region\", host=~\"$host\"}))",
       "legendFormat": "Total Out"
      },
      {
       "expr": "topk_avg(5,\n  sum(rate(fly_edge_data_out\n    {app=~\"$app\",region=~\"$region\", host=~\"$host\"}))by(region)\n, \"region=other\") > 0",
       "legendFormat": "{{region}}"
      }
     ]
    }
   ]
  },
  {
   "title": "TCP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Connects / disconnects",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "sum(increase(fly_edge_tcp_connects_count{app=~\"$app\",region=~\"$region\",host=~\"$host\"})) > 0",
       "legendFormat": "connects"
      },
      {
       "expr": "sum(increase(fly_edge_tcp_disconnects_count{app=~\"$app\",region=~\"$region\",host=~\"$host\"})) > 0",
       "legendFormat": "disconnects"
      }
     ]
    },
    {
     "title": "Rate limits",
     "type": "timeseries",
     "description": "Servers have a limit on how many TCP connections they will accept and how many TLS handshakes they will process each second. When these limits are reached, incoming connections are dropped. This chart shows how many connections have been dropped per rate limit type.",
     "gridPos": { "x": 12, "y": 2, "w": 12, "h": 8 },
     "targets": [
      {
       "expr": "sum(increase(fly_edge_tcp_rate_limited_count{app=~\"$app\",region=~\"$region\",host=~\"$host\"})) by (type, region) > 0",
       "legendFormat": "{{type}} - {{region}}"
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Responses Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "sum(increase(fly_edge_http_responses_count{app=~\"$app\",region=~\"$region\",host=~\"$host\"})) by (status)",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "Response Time",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantiles(\"p\", 0.5, 0.9, 0.99, sum(increase(fly_edge_http_response_time_seconds_bucket{app=~\"$app\",region=~\"$region\",host=~\"$host\"}[1m]))by(le))",
       "legendFormat": "p{{p}}"
      },
      {
       "expr": "sum(increase(fly_edge_http_response_time_seconds_sum{app=~\"$app\",region=~\"$region\",host=~\"$host\"})) / sum(increase(fly_edge_http_response_time_seconds_count{app=~\"$app\",region=~\"$region\",host=~\"$host\"}))",
       "legendFormat": "avg"
      }
     ]
    },
    {
     "title": "Response Time",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
     "targets": [
      {
       "expr": "sum(increase(fly_edge_http_response_time_seconds_bucket{app=~\"$app\",region=~\"$region\",host=~\"$host\"})) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "TLS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Handshake times (bucketed)",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 4 },
     "targets": [
      {
       "expr": "sum(increase(fly_edge_tls_handshake_time_seconds_bucket{app=\"$app\",region=~\"$region\",host=~\"$host\"})) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Handshakes",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "  sum(increase(fly_edge_tls_handshake_time_seconds_count\n    {app=~\"$app\",region=~\"$region\", host=~\"$host\"})) > 0",
       "legendFormat": "Total"
      },
      {
       "expr": "topk_avg(5,\n  sum(increase(fly_edge_tls_handshake_time_seconds_count\n    {app=~\"$app\",region=~\"$region\", host=~\"$host\"}))by(region) > 0\n, \"region=other\")",
       "legendFormat": "{{region}}"
      }
     ]
    },
    {
     "title": "SNI limit reached",
     "type": "timeseries",
     "description": "Servers have a limit on how many TLS handshakes they will process concurrently per servername indicator. When this limit is reached, we queue handshakes up to a point. This chart shows how often the limit was reached during an interval.",
     "gridPos": { "h": 7, "w": 7, "x": 16, "y": 4 },
     "targets": [
      {
       "expr": "sum(increase(fly_edge_tls_sni_limit_reached_count{app=~\"^$app$\",region=~\"^$region$\",host=~\"^$host$\"})) by (servername) > 0",
       "legendFormat": "{{servername}}"
      }
     ]
    },
    {
     "title": "Handshake errors",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 9, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "sum(increase(fly_edge_tls_handshake_errors{app=~\"$app\",region=~\"$region\",host=~\"$host\"}))by(host,region) > 0",
       "legendFormat": "{{host}} - {{region}}"
      }
     ]
    },
    {
     "title": "IP limit reached",
     "type": "timeseries",
     "description": "Servers have a limit on how many TLS handshakes they will process concurrently per IP block. When this limit is reached, we queue handshakes up to a point. This chart shows how often the limit was reached during an interval.",
     "gridPos": { "h": 7, "w": 7, "x": 9, "y": 11 },
     "targets": [
      {
       "expr": "sum(increase(fly_edge_tls_ip_limit_reached_count{app=~\"^$app$\",region=~\"^$region$\",host=~\"^$host$\"})) by (ip) > 0",
       "legendFormat": "{{ip}}"
      }
     ]
    },
    {
     "title": "Handshake queue times (bucketed)",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 11 },
     "targets": [
      {
       "expr": "sum(increase(fly_edge_tls_queue_time_seconds_bucket{app=~\"^$app$\",region=~\"^$region$\",host=~\"^$host$\"}[$__interval])) by (le) > 0",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Fly Edge Errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "targets": [
      {
       "expr": "sum by(app, region) (increase(fly_edge_error_count{app=~\"$app\",region=~\"$region\"}))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}