{
 "title": "Fly Instance",
 "tags": [ "fly" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "app",
    "label": "App",
    "query": {
     "query": "label_values(fly_instance_up, app)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(fly_instance_up{app=\"$app\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Proxy",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP Responses Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(fly_app_http_responses_count{app=\"$app\", instance=~\"$instance\"})) by (status)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "HTTP Response Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(increase(fly_app_http_response_time_seconds_sum{app=\"$app\", instance=~\"$instance\"}))/sum(increase(fly_app_http_response_time_seconds_count{app=\"$app\", instance=~\"$instance\"}))",
       "legendFormat": "avg"
      },
      {
       "expr": "histogram_quantiles(\"p\", 0.5, 0.9, 0.99, sum(increase(fly_app_http_response_time_seconds_bucket{app=\"$app\", instance=~\"$instance\"}))by(le))",
       "legendFormat": "p{{p}}"
      }
     ]
    },
    {
     "title": "Soft Limit Reached",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "increase(fly_app_soft_limit_reached_count{app=~\"$app\",instance=~\"$instance\"}) > 0",
       "legendFormat": "count"
      }
     ]
    },
    {
     "title": "Hard Limit Reached",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "increase(fly_app_hard_limit_reached_count{app=~\"$app\",instance=~\"$instance\"}) > 0",
       "legendFormat": "count"
      }
     ]
    },
    {
     "title": "App Concurrency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "targets": [
      {
       "expr": "sum(fly_app_concurrency{app=\"$app\", instance=~\"$instance\"}) by(app, instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Instance Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory - Basic",
     "type": "timeseries",
     "description": "`Available`: An estimate of how much (non-`Free`) memory is available for starting new applications, without swapping.",
     "gridPos": { "h": 9, "w": 10, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "fly_instance_memory_mem_total{instance=\"$instance\"}",
       "legendFormat": "Total"
      },
      {
       "expr": "fly_instance_memory_mem_total{instance=\"$instance\"}\n\n- max({__name__=~\"fly_instance_memory_mem_(available|free)\", instance=\"$instance\"})\n\n+ max(0, fly_instance_memory_mem_free{instance=\"$instance\"} - fly_instance_memory_mem_available{instance=\"$instance\"})",
       "legendFormat": "Used"
      },
      {
       "expr": "fly_instance_memory_mem_available{instance=\"$instance\"} - fly_instance_memory_mem_free{instance=\"$instance\"} > 0",
       "legendFormat": "Available"
      },
      {
       "expr": "min({__name__=~\"fly_instance_memory_mem_(available|free)\",instance=\"$instance\"})",
       "legendFormat": "Free"
      }
     ]
    },
    {
     "title": "Memory - Detailed",
     "type": "timeseries",
     "description": "* `Total`: Total usable ram (i.e. physical ram minus a few reserved bits and the kernel binary code)\n* `Available`: An estimate of how much memory is available for starting new applications, without swapping\n* `Buffers`: Relatively temporary storage for raw disk blocks - shouldn't get tremendously large (20MB or so)\n* `Cached`: in-memory cache for files read from the disk (the pagecache).  Doesn't include `SwapCached`\n",
     "gridPos": { "h": 9, "w": 10, "x": 10, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "fly_instance_memory_mem_total{instance=\"$instance\"}",
       "legendFormat": "Total - Total usable ram (i.e. physical ram minus a few reserved bits)"
      },
      {
       "expr": "fly_instance_memory_mem_total{instance=\"$instance\"} - \nfly_instance_memory_mem_free{instance=\"$instance\"} - \nfly_instance_memory_buffers{instance=\"$instance\"} - \nfly_instance_memory_cached{instance=\"$instance\"} - \nfly_instance_memory_slab{instance=\"$instance\"} -\nfly_instance_memory_writeback{instance=\"$instance\"} -\nfly_instance_memory_dirty{instance=\"$instance\"} -\nfly_instance_memory_vmalloc_used{instance=\"$instance\"}",
       "legendFormat": "Used - misc memory used by user-space applications"
      },
      {
       "expr": "fly_instance_memory_vmalloc_used{instance=\"$instance\"}",
       "legendFormat": "VmallocUsed - amount of vmalloc area which is used"
      },
      {
       "expr": "fly_instance_memory_slab{instance=\"$instance\"}",
       "legendFormat": "Slab - In-kernel data structures cache"
      },
      {
       "expr": "fly_instance_memory_buffers{instance=\"$instance\"}",
       "legendFormat": "Buffers - Relatively temporary storage for raw disk blocks"
      },
      {
       "expr": "fly_instance_memory_dirty{instance=\"$instance\"}",
       "legendFormat": "Dirty - Memory which is waiting to get written back to the disk"
      },
      {
       "expr": "fly_instance_memory_writeback{instance=\"$instance\"}",
       "legendFormat": "Writeback - Memory which is actively being written back to the disk"
      },
      {
       "expr": "fly_instance_memory_cached{instance=\"$instance\"}",
       "legendFormat": "Cached - In-memory cache for files read from the disk (the pagecache)"
      },
      {
       "expr": "fly_instance_memory_mem_free{instance=\"$instance\"}",
       "legendFormat": "Free - Unassigned memory"
      },
      {
       "expr": "fly_instance_memory_swap_total{instance=\"$instance\"} -\nfly_instance_memory_swap_free{instance=\"$instance\"} -\nfly_instance_memory_swap_cached{instance=\"$instance\"}",
       "legendFormat": "SwapUsed - Memory which has been evicted from RAM, and is temporarily on the disk"
      },
      {
       "expr": "fly_instance_memory_swap_cached{instance=\"$instance\"}",
       "legendFormat": "SwapCached - Memory that was swapped back in but still also is in the swapfile"
      },
      {
       "expr": "fly_instance_memory_swap_total{app=\"wjordan-grafana\",instance=\"789d2449\"}",
       "legendFormat": "SwapTotal - total amount of swap space available"
      }
     ]
    },
    {
     "title": "Memory Active / Inactive",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 9, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "fly_instance_memory_inactive{instance=\"$instance\"}",
       "legendFormat": "Inactive - Memory which has been less recently used.  It is more eligible to be reclaimed for other purposes"
      },
      {
       "expr": "fly_instance_memory_active{instance=\"$instance\"}",
       "legendFormat": "Active - Memory that has been used more recently and usually not reclaimed unless absolutely necessary."
      }
     ]
    },
    {
     "title": "Vmalloc",
     "type": "timeseries",
     "description": "total size of vmalloc memory area",
     "gridPos": { "h": 7, "w": 5, "x": 9, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(fly_instance_memory_vmalloc_total{instance=~\"$instance\"})",
       "legendFormat": "VmallocTotal"
      },
      {
       "expr": "fly_instance_memory_vmalloc_chunk{instance=~\"$instance\"}",
       "legendFormat": "VmallocChunk"
      }
     ]
    },
    {
     "title": "Shared Memory",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 14, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "fly_instance_memory_shmem{instance=\"$instance\"}",
       "legendFormat": "Shmem - Total memory used by shared memory (shmem) and tmpfs"
      }
     ]
    }
   ]
  },
  {
   "title": "Instance Load and CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Load Average",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 7, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sort_by_label(\nlabel_replace(\n  sum(fly_instance_load_average{instance=\"$instance\"})by(minutes) / \n  sum(count(fly_instance_cpu{instance=\"$instance\", mode=\"idle\"})without(cpu))\n, \"minutes2\", \"$1\", \"minutes\", \"(..)\")\n, \"minutes2\", \"minutes\")",
       "legendFormat": "{{minutes}}min"
      }
     ]
    },
    {
     "title": "CPU Utilization",
     "type": "timeseries",
     "description": "* `baseline`: baseline CPU utilization threshold for your Machine type. Your instance can burst above this threshold, but only for short periods.\n* `steal`: Percentage of time the virtual CPU was waiting on a CPU in use by other VMs, due to throttling or other CPU contention on the host.",
     "gridPos": { "h": 8, "w": 9, "x": 7, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(sum(rate(fly_instance_cpu{instance=\"$instance\",mode!=\"idle\",mode!=\"steal\"}[60s]))by(mode)>0) / count(fly_instance_cpu{instance=\"$instance\",mode=\"idle\"})",
       "legendFormat": "{{mode}}"
      },
      {
       "expr": "(sum(rate(fly_instance_cpu{instance=\"$instance\",mode=\"steal\"}[60s]))by(mode)>0) / count(fly_instance_cpu{instance=\"$instance\",mode=\"idle\"}) > 1",
       "legendFormat": "{{mode}}"
      },
      {
       "expr": "fly_instance_cpu_baseline{app=\"$app\", instance=\"$instance\"} /\ncount(fly_instance_cpu{app=\"$app\", instance=\"$instance\", mode=\"idle\"})without(cpu_id, mode) * 100",
       "legendFormat": "baseline"
      }
     ]
    },
    {
     "title": "Per-CPU Utilization",
     "type": "timeseries",
     "description": "* `baseline`: baseline CPU utilization threshold for your Machine type. Your instance can burst above this threshold, but only for short periods.\n* `steal`: Percentage of time the virtual CPU was waiting on a CPU in use by other VMs, due to throttling or other CPU contention on the host.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum(rate(fly_instance_cpu{instance=\"$instance\",mode!=\"idle\",mode!=\"steal\"}[60s]))by(cpu_id)",
       "legendFormat": "cpu {{cpu_id}}"
      },
      {
       "expr": "fly_instance_cpu_baseline{app=\"$app\", instance=\"$instance\"} /\ncount(fly_instance_cpu{app=\"$app\", instance=\"$instance\", mode=\"idle\"})without(cpu_id, mode) * 100",
       "legendFormat": "baseline"
      },
      {
       "expr": "sum(rate(fly_instance_cpu{instance=\"$instance\",mode=\"steal\"}[60s]))by(cpu_id)",
       "legendFormat": "steal {{cpu_id}}"
      }
     ]
    },
    {
     "title": "CPU Quota Balance and Throttling",
     "type": "timeseries",
     "description": "Aggregate across all CPUs.\n* `baseline`: baseline CPU utilization threshold for your Machine type. Your instance can burst above this threshold, but only for short periods.\n* `balance`: Accumulated burst balance in seconds.\n* `throttled`: Percentage of time your instance was throttled to its baseline performance.\n* `steal`: Percentage of time the instance was waiting on a CPU in use by other VMs, due to throttling or other CPU contention on the host.",
     "gridPos": { "h": 8, "w": 9, "x": 7, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(sum(rate(fly_instance_cpu{instance=\"$instance\",mode!=\"idle\",mode!=\"steal\"}[60s]))) / count(fly_instance_cpu{instance=\"$instance\",mode=\"idle\"})",
       "legendFormat": "utilization"
      },
      {
       "expr": "(sum(rate(fly_instance_cpu{instance=\"$instance\",mode=\"steal\"}[60s]))by(mode)>0) / count(fly_instance_cpu{instance=\"$instance\",mode=\"idle\"}) > 1",
       "legendFormat": "steal"
      },
      {
       "expr": "fly_instance_cpu_baseline{app=\"$app\", instance=\"$instance\"} /\ncount(fly_instance_cpu{app=\"$app\", instance=\"$instance\", mode=\"idle\"})without(cpu_id, mode) * 100",
       "legendFormat": "baseline"
      },
      {
       "expr": "min_over_time(fly_instance_cpu_balance{app=\"$app\", instance=\"$instance\"}[60s]) /\ncount(fly_instance_cpu{app=\"$app\", instance=\"$instance\", mode=\"idle\"})without(cpu_id, mode) / 100",
       "legendFormat": "balance"
      },
      {
       "expr": "rate(fly_instance_cpu_throttle{app=\"$app\", instance=\"$instance\"}[60s]) /\ncount(fly_instance_cpu{app=\"$app\", instance=\"$instance\", mode=\"idle\"})without(cpu_id, mode) > 1",
       "legendFormat": "throttle"
      }
     ]
    }
   ]
  },
  {
   "title": "Instance Disks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk I/O",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "rate(fly_instance_disk_reads_completed{instance=\"$instance\"})",
       "legendFormat": "{{device}} - Reads"
      },
      {
       "expr": "rate(fly_instance_disk_writes_completed{instance=\"$instance\"})",
       "legendFormat": "{{device}} - Writes"
      }
     ]
    },
    {
     "title": "Disk R/W Data",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(fly_instance_disk_sectors_read{instance=\"$instance\"}) * 512",
       "legendFormat": "{{device}} - Read"
      },
      {
       "expr": "rate(fly_instance_disk_sectors_written{instance=\"$instance\"}) * 512",
       "legendFormat": "{{device}} - Written"
      }
     ]
    },
    {
     "title": "Disk I/O Merged",
     "type": "timeseries",
     "description": "Reads and writes which are adjacent to each other may be merged for efficiency.  Thus two 4K reads may become one 8K read before it is ultimately handed to the disk, and so it will be counted (and queued) as only one I/O.  This field lets you know how often this was done.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "rate(fly_instance_disk_reads_merged{instance=\"$instance\"})",
       "legendFormat": "{{device}} - Reads"
      },
      {
       "expr": "rate(fly_instance_disk_writes_merged{instance=\"$instance\"})",
       "legendFormat": "{{device}} - Writes"
      }
     ]
    },
    {
     "title": "I/O Utilization",
     "type": "timeseries",
     "description": "Proportion of each second spent doing I/Os.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "rate(fly_instance_disk_time_io{instance=\"$instance\"}) / 1000",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Average Queue Depth",
     "type": "timeseries",
     "description": "`disk_time_io_weighted` provides an easy measure of both I/O completion time and the backlog that may be accumulating.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(fly_instance_disk_time_io_weighted{instance=\"$instance\"}) / 1000",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Average I/O Duration",
     "type": "timeseries",
     "description": "Total number of seconds spent by all reads/writes divided by the total number of reads/writes completed successfully.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "rate(fly_instance_disk_time_reading{instance=\"$instance\"}) / rate(fly_instance_disk_reads_completed{instance=\"$instance\"})",
       "legendFormat": "{{device}} - Reads"
      },
      {
       "expr": "rate(fly_instance_disk_time_writing{instance=\"$instance\"}) / rate(fly_instance_disk_writes_completed{instance=\"$instance\"})",
       "legendFormat": "{{device}} - Writes"
      }
     ]
    }
   ]
  },
  {
   "title": "Instance Networking",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "rate(fly_instance_net_recv_bytes{device='eth0', instance=\"$instance\"}) * 8",
       "legendFormat": "recv"
      },
      {
       "expr": "rate(fly_instance_net_sent_bytes{device='eth0', instance=\"$instance\"}) * 8",
       "legendFormat": "sent"
      }
     ]
    },
    {
     "title": "Packets",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "rate(fly_instance_net_recv_packets{device='eth0',instance=\"$instance\"})",
       "legendFormat": "recv"
      },
      {
       "expr": "rate(fly_instance_net_sent_packets{device='eth0',instance=\"$instance\"})",
       "legendFormat": "sent"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "rate(fly_instance_net_recv_errs{device='eth0',instance=\"$instance\"})",
       "legendFormat": "recv"
      },
      {
       "expr": "rate(fly_instance_net_sent_errs{device='eth0',instance=\"$instance\"})",
       "legendFormat": "sent"
      }
     ]
    },
    {
     "title": "Drop",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "rate(fly_instance_net_recv_drop{device='eth0',instance=\"$instance\"})",
       "legendFormat": "recv"
      },
      {
       "expr": "rate(fly_instance_net_sent_drop{device='eth0',instance=\"$instance\"})",
       "legendFormat": "sent"
      }
     ]
    },
    {
     "title": "Fifo",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "rate(fly_instance_net_recv_fifo{device='eth0', instance=\"$instance\"})",
       "legendFormat": "recv"
      },
      {
       "expr": "rate(fly_instance_net_sent_fifo{device='eth0', instance=\"$instance\"})",
       "legendFormat": "sent"
      }
     ]
    },
    {
     "title": "Frame",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "rate(fly_instance_net_recv_frame{device='eth0', instance=\"$instance\"})",
       "legendFormat": "recv"
      }
     ]
    },
    {
     "title": "Compressed",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "rate(fly_instance_net_recv_compressed{device='eth0',instance=\"$instance\"})",
       "legendFormat": "recv"
      },
      {
       "expr": "rate(fly_instance_net_sent_compressed{device='eth0',instance=\"$instance\"})",
       "legendFormat": "sent"
      }
     ]
    },
    {
     "title": "Multicast",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "rate(fly_instance_net_recv_multicast{device='eth0',instance=\"$instance\"})",
       "legendFormat": "recv"
      }
     ]
    },
    {
     "title": "Colls",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "rate(fly_instance_net_sent_colls{device='eth0', instance=\"$instance\"})",
       "legendFormat": "sent"
      }
     ]
    },
    {
     "title": "Carrier",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "rate(fly_instance_net_sent_carrier{device='eth0', instance=\"$instance\"})",
       "legendFormat": "sent"
      }
     ]
    }
   ]
  },
  {
   "title": "Instance File Descriptors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "File Descriptors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "fly_instance_filefd_allocated{instance=\"$instance\"}",
       "legendFormat": "Allocated"
      },
      {
       "expr": "fly_instance_filefd_maximum{instance=\"$instance\"}",
       "legendFormat": "Maximum"
      }
     ]
    }
   ]
  },
  {
   "title": "Volumes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Root Volume Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "label_replace(fly_instance_filesystem_blocks{app=\"$app\", instance=\"$instance\",mount=\"/.fly-upper-layer\"} * fly_instance_filesystem_block_size{app=\"$app\", instance=\"$instance\",mount=\"/.fly-upper-layer\"}, \"mount\", \"/\", \"mount\", \"/.fly-upper-layer\")",
       "legendFormat": "{{mount}} ({{instance}} - {{region}}) Total"
      },
      {
       "expr": "label_replace(fly_instance_filesystem_blocks{app=\"$app\", instance=\"$instance\", mount=\"/.fly-upper-layer\"} * fly_instance_filesystem_block_size{app=\"$app\", instance=\"$instance\",mount=\"/.fly-upper-layer\"} - fly_instance_filesystem_blocks_avail{app=\"$app\", instance=\"$instance\", mount=\"/.fly-upper-layer\"} * fly_instance_filesystem_block_size{app=\"$app\", instance=\"$instance\", mount=\"/.fly-upper-layer\"},\"mount\", \"/\", \"mount\", \"/.fly-upper-layer\")",
       "legendFormat": "{{mount}} ({{instance}} - {{region}}) Used"
      }
     ]
    },
    {
     "title": "Fly Volume Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "fly_instance_filesystem_blocks{app=\"$app\", instance=\"$instance\", mount!=\"/\",mount!=\"/.fly-upper-layer\"} * fly_instance_filesystem_block_size{app=\"$app\", instance=\"$instance\", mount!=\"/\",mount!=\"/.fly-upper-layer\"}",
       "legendFormat": "{{mount}} ({{instance}} - {{region}}) Total"
      },
      {
       "expr": "fly_instance_filesystem_blocks{app=\"$app\", instance=\"$instance\", mount!=\"/\",mount!=\"/.fly-upper-layer\"} * fly_instance_filesystem_block_size{app=\"$app\", instance=\"$instance\", mount!=\"/\",mount!=\"/.fly-upper-layer\"} - fly_instance_filesystem_blocks_avail{app=\"$app\", instance=\"$instance\", mount!=\"/\",mount!=\"/.fly-upper-layer\"} * fly_instance_filesystem_block_size{app=\"$app\", instance=\"$instance\", mount!=\"/\",mount!=\"/.fly-upper-layer\"}",
       "legendFormat": "{{mount}} ({{instance}} - {{region}}) Used"
      }
     ]
    }
   ]
  }
 ]
}