{
 "title": "Fly App",
 "description": "General Fly App metrics.",
 "tags": [ "fly" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "app",
    "label": "App",
    "query": {
     "query": "label_values(fly_instance_up, app)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "logs",
     "gridPos": { "h": 8, "w": 19, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "fly.app.name: $app",
       "metrics": [
        { "id": "1", "settings": { "limit": "1000" }, "type": "logs" }
       ],
       "query": "fly.app.name:\"$app\""
      }
     ]
    },
    {
     "title": "Log volume",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 5, "x": 19, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "trimEdges": "1" }, "type": "date_histogram" }
       ],
       "expr": "fly.app.name: $app | stats count() as logs",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "fly.app.name:\"$app\""
      }
     ]
    }
   ]
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Data Out",
   "type": "geomap",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "label_uppercase(sum(rate(fly_edge_data_out{app=\"$app\"}[$__range]))by(region), \"region\") > 0",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_uppercase(sum(rate(fly_instance_net_sent_bytes{app=\"$app\"}[$__range]))by(region), \"region\") > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Data Out",
   "type": "table",
   "gridPos": { "h": 10, "w": 5, "x": 11, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "topk_avg(5, sum(rate(fly_edge_data_out{app=\"$app\"}[$__range]) > 0)by(region), \"region=other\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "topk_avg(5, sum(rate(fly_instance_net_sent_bytes{app=\"$app\"}[$__range]) > 0)by(region), \"region=other\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(fly_instance_net_recv_bytes{app=\"$app\",device=\"eth0\"}))",
     "legendFormat": "Total Received"
    },
    {
     "expr": "topk_avg(5,\n  sum(rate(fly_instance_net_recv_bytes\n    {app=~\"$app\",device=\"eth0\"}))by(instance,region)\n, \"region=Other\") > 0",
     "legendFormat": "{{instance}} - {{region}}"
    },
    {
     "expr": "sum(rate(fly_instance_net_sent_bytes{app=\"$app\",device=\"eth0\"}))",
     "legendFormat": "Total Sent"
    },
    {
     "expr": "topk_avg(5,\n  sum(rate(fly_instance_net_sent_bytes\n    {app=~\"$app\",device=\"eth0\"}))by(instance,region)\n, \"region=Other\") > 0",
     "legendFormat": "{{instance}} - {{region}}"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "mode(fly_instance_memory_mem_total{app=\"$app\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "fly_instance_memory_mem_total{app=\"$app\"} - fly_instance_memory_mem_available{app=\"$app\"}",
     "legendFormat": "{{instance}} - {{region}}"
    },
    {
     "expr": "(fly_instance_memory_swap_total{app=\"$app\"} -\nfly_instance_memory_swap_free{app=\"$app\"}) > 0",
     "legendFormat": "SwapUsed - Memory which has been evicted from RAM, and is temporarily on the disk"
    },
    {
     "expr": "(fly_instance_memory_swap_total{app=\"$app\"}) > 0",
     "legendFormat": "SwapTotal - total amount of swap space available"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "description": "Per-instance aggregate across all CPUs.\n* `baseline`: baseline CPU performance for your Machine type. Your instance can burst above this threshold, but only for short periods.\n* `throttled`: Percentage of time your instance was throttled to its baseline performance.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(increase(fly_instance_cpu{app=\"$app\", mode!=\"idle\",mode!=\"steal\"}[60s]))by(instance, region)/60 / \n  sum(count(fly_instance_cpu{app=\"$app\", mode=\"idle\"})without(cpu))by(instance, region)",
     "legendFormat": "{{instance}} - {{region}}"
    },
    {
     "expr": "mode(fly_instance_cpu_baseline{app=\"$app\"}) /\nmode(count(fly_instance_cpu{app=\"$app\", mode=\"idle\"})without(cpu_id, mode)) * 100",
     "legendFormat": "baseline"
    },
    {
     "expr": "avg(rate(fly_instance_cpu_throttle{app=\"$app\"}[60s])/\ncount(fly_instance_cpu{app=\"$app\", mode=\"idle\"})without(cpu_id, mode))>1",
     "legendFormat": "throttled"
    }
   ]
  },
  {
   "title": "App Concurrency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum(fly_app_concurrency{app=\"$app\"})by(instance, region)",
     "legendFormat": "{{instance}} - {{region}}"
    }
   ]
  },
  {
   "title": "5min Load Avg",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(fly_instance_load_average{app=\"$app\",minutes=\"5\"})by(instance, region) /\n  sum(count(fly_instance_cpu{app=\"$app\", mode=\"idle\"})without(cpu))by(instance, region)",
     "legendFormat": "{{instance}} - {{region}}"
    }
   ]
  },
  {
   "title": "HTTP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP Response Count",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(fly_app_http_responses_count{app=\"$app\"})) by (status) > 0",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Edge HTTP Response Count / Latency",
     "type": "geomap",
     "description": "* Size: Count\n* Color: Latency",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "label_uppercase(\n    sum(\n        increase(fly_edge_http_response_time_seconds_count{app=\"$app\"}[$__range])\n        )by(region,le) / \n    max(sum(\n        increase(fly_edge_http_response_time_seconds_count{app=\"$app\"}[$__range])\n        )by(region,le))\n    , \"region\")",
       "legendFormat": "__auto"
      },
      {
       "expr": "label_uppercase(\n  sum(increase(\n    fly_edge_http_response_time_seconds_sum{app=\"$app\"}[$__range]\n    ))by(region) /\n  sum(increase(\n    fly_edge_http_response_time_seconds_count{app=\"$app\"}[$__range]\n    ))by(region)\n  , \"region\") * 1000",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "HTTP Response Times",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(increase(fly_app_http_response_time_seconds_sum{app=\"$app\"}))/sum(increase(fly_app_http_response_time_seconds_count{app=\"$app\"}))",
       "legendFormat": "avg"
      },
      {
       "expr": "histogram_quantiles(\"p\", 0.5, 0.9, 0.99, sum(increase(fly_app_http_response_time_seconds_bucket{app=\"$app\"}))by(le))",
       "legendFormat": "p{{p}}"
      }
     ]
    },
    {
     "title": "HTTP Response Time Avg",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(increase(fly_app_http_response_time_seconds_sum{app=\"$app\"}))by(instance,region)/sum(increase(fly_app_http_response_time_seconds_count{app=\"$app\"}))by(instance,region)",
       "legendFormat": "{{instance}} - {{region}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Volumes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Root Filesystem Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "label_replace(mode(fly_instance_filesystem_blocks{app=~\"^$app$\",mount=\"/.fly-upper-layer\"} * fly_instance_filesystem_block_size{app=~\"^$app$\",mount=\"/.fly-upper-layer\"}) by (mount),\"mount\", \"/\", \"mount\", \"/.fly-upper-layer\")",
       "legendFormat": "{{mount}} Total"
      },
      {
       "expr": "label_replace(fly_instance_filesystem_blocks{app=~\"^$app$\", mount=\"/.fly-upper-layer\"} * fly_instance_filesystem_block_size{app=~\"^$app$\", mount=\"/.fly-upper-layer\"} - fly_instance_filesystem_blocks_avail{app=~\"^$app$\",mount=\"/.fly-upper-layer\"} * fly_instance_filesystem_block_size{app=~\"^$app$\",mount=\"/.fly-upper-layer\"},\"mount\", \"/\", \"mount\", \"/.fly-upper-layer\")",
       "legendFormat": "{{mount}} ({{instance}} - {{region}}) Used"
      }
     ]
    },
    {
     "title": "Fly Volume Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "mode(fly_instance_filesystem_blocks{app=~\"^$app$\", mount!=\"/\",mount!=\"/.fly-upper-layer\"} * fly_instance_filesystem_block_size{app=~\"^$app$\", mount!=\"/\",mount!=\"/.fly-upper-layer\"})",
       "legendFormat": "{{mount}} Total"
      },
      {
       "expr": "fly_instance_filesystem_blocks{app=~\"^$app$\", mount!=\"/\",mount!=\"/.fly-upper-layer\"} * fly_instance_filesystem_block_size{app=~\"^$app$\", mount!=\"/\",mount!=\"/.fly-upper-layer\"} - fly_instance_filesystem_blocks_avail{app=~\"^$app$\",mount!=\"/\",mount!=\"/.fly-upper-layer\"} * fly_instance_filesystem_block_size{app=~\"^$app$\",mount!=\"/\",mount!=\"/.fly-upper-layer\"}",
       "legendFormat": "{{mount}} ({{instance}} - {{region}}) Used"
      }
     ]
    }
   ]
  }
 ]
}